[workspace]
members = [
    "bin",
    "imag-bookmark",
    "imag-counter",
    "imag-diary",
    "imag-link",
    "imag-notes",
    "imagrc.toml",
    "imag-ref",
    "imag-store",
    "imag-tag",
    "imag-todo",
    "imag-view",
    "libimagbookmark",
    "libimagcliutil",
    "libimagcounter",
    "libimagdiary",
    "libimagentryfilter",
    "libimagentrylink",
    "libimagentrylist",
    "libimagentrymarkdown",
    "libimagentrymarkup",
    "libimagentryselect",
    "libimagentrytag",
    "libimagentryview",
    "libimagerror",
    "libimaginteraction",
    "libimagnotes",
    "libimagnotification",
    "libimagref",
    "libimagrt",
    "libimagstore",
    "libimagstorestdhook",
    "libimagtimeui",
    "libimagtodo",
    "libimagutil",
]
