[package]
name = "imag"
version = "0.2.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Personal information management (PIM) suite"
keywords = ["pim", "personal", "information", "management", "suite"]
readme        = "./README.md"
license       = "LGPL-2.1"

website = "http://imag-pim.org"
documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository = "https://github.com/matthiasbeyer/imag"

[dependencies]

[workspace]
members = [
    "bin",
    "imag-bookmark",
    "imag-counter",
    "imag-diary",
    "imag-link",
    "imag-notes",
    "imagrc.toml",
    "imag-ref",
    "imag-store",
    "imag-tag",
    "imag-todo",
    "imag-view",
    "libimagbookmark",
    "libimagcliutil",
    "libimagcounter",
    "libimagdiary",
    "libimagentryfilter",
    "libimagentrylink",
    "libimagentrylist",
    "libimagentrymarkdown",
    "libimagentrymarkup",
    "libimagentryselect",
    "libimagentrytag",
    "libimagentryview",
    "libimagerror",
    "libimaginteraction",
    "libimagnotes",
    "libimagnotification",
    "libimagref",
    "libimagrt",
    "libimagstore",
    "libimagstorestdhook",
    "libimagtimeui",
    "libimagtodo",
    "libimagutil",
]

