[package]
name = "libimagrt"
version = "0.2.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

[profile.dev]
codegen-units = 2

[dependencies]
clap = "2.*"
env_logger = "0.3"
toml = "0.2.*"
log = "0.3"
xdg-basedir = "0.2.2"
itertools = "0.4"
tempfile = "2.1.1"
ansi_term = "0.7"

[dependencies.libimagstore]
path = "../libimagstore"

[dependencies.libimagstorestdhook]
path = "../libimagstorestdhook"

[dependencies.libimagutil]
path = "../libimagutil"

[dependencies.libimagerror]
path = "../libimagerror"

