[package]
name = "libimagentrylist"
version = "0.2.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

[profile.dev]
codegen-units = 2

[dependencies]
clap = "2.*"
log = "0.3"
toml = "0.2.*"
prettytable-rs = "0.6.*"

[dependencies.libimagstore]
path = "../libimagstore"

[dependencies.libimagerror]
path = "../libimagerror"

[dependencies.libimagutil]
path = "../libimagutil"

