[package]
name = "libimagstore"
version = "0.2.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

[profile.dev]
codegen-units = 2

[dependencies]
fs2 = "0.2"
glob = "0.2.11"
lazy_static = "0.1.15"
log = "0.3"
regex = "0.1"
semver = "0.2"
toml = "0.2.*"
version = "2.0.1"
crossbeam = "0.2.8"
walkdir = "0.1.5"

[dependencies.libimagerror]
path = "../libimagerror"

[dependencies.libimagutil]
path = "../libimagutil"

[dev-dependencies]
tempdir = "0.3.4"
env_logger = "0.3"

[features]
default = []
verify  = []

