[package]
name = "libimagstorestdhook"
version = "0.2.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

[dependencies]
toml = "0.2.*"
log = "0.3"
fs2 = "0.2"
git2 = "0.4"

[dependencies.libimagstore]
path = "../libimagstore"

[dependencies.libimagentrylink]
path = "../libimagentrylink"

[dependencies.libimaginteraction]
path = "../libimaginteraction"

[dependencies.libimagerror]
path = "../libimagerror"

[dependencies.libimagutil]
path = "../libimagutil"

