[package]
name = "libimagutil"
version = "0.2.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

[profile.dev]
codegen-units = 2

[dependencies]
lazy_static = "0.1.15"
log = "0.3"
regex = "0.1"
tempfile = "2.1.1"

